% MATLAB script to plot controller response from CSV files
% This script reads CSV files generated by test_all_controllers.exe
% and plots the response of different PID controllers for comparison

clear;
close all;
clc;

% Define the directory where CSV files are located
% Change this path to match your actual build directory
csv_dir = '/';

% List of controller types and their corresponding CSV files
controllers = {
    'Position PID', 'pid_response.csv';
    'Incremental PID', 'incremental_pid_response.csv';
    'Fuzzy PID', 'fuzzy_pid_response.csv';
    'Adaptive PID', 'adaptive_pid_response.csv'
};

% Define colors for each controller
colors = {'r', 'g', 'b', 'm'};

% Create a figure for the main response comparison
figure('Name', 'Controller Response Comparison', 'Position', [100, 100, 1200, 800]);

% Initialize metrics matrix
metrics = zeros(4, 4);

% Read and plot data for each controller
for i = 1:size(controllers, 1)
    controller_name = controllers{i, 1};
    csv_file = fullfile(csv_dir, controllers{i, 2});
    color = colors{i};
    
    % Check if the CSV file exists
    if ~exist(csv_file, 'file')
        warning('CSV file not found: %s', csv_file);
        continue;
    end
    
    % Read CSV data
    % The CSV format is: time,setpoint,process_val,output
    data = readmatrix(csv_file);
    time = data(:, 1);
    setpoint = data(:, 2);
    process_val = data(:, 3);
    output = data(:, 4);
    
    % Plot process value (response) vs time
    subplot(3, 2, 1);
    hold on;
    plot(time, process_val, color, 'LineWidth', 2);
    grid on;
    xlabel('Time (s)');
    ylabel('Process Value');
    title('Controller Response Comparison');
    legend('show');
    
    % Plot output vs time
    subplot(3, 2, 2);
    hold on;
    plot(time, output, color, 'LineWidth', 2);
    grid on;
    xlabel('Time (s)');
    ylabel('Controller Output');
    title('Controller Output Comparison');
    legend('show');
    
    % Calculate and plot performance metrics
    % Rise time: Time to go from 10% to 90% of final value
    final_value = setpoint(end);
    low_threshold = 0.1 * final_value;
    high_threshold = 0.9 * final_value;
    
    % Find rise time
    rise_time_idx = find(process_val >= high_threshold, 1);
    rise_time = 0;
    if ~isempty(rise_time_idx)
        rise_time = time(rise_time_idx);
    end
    
    % Find overshoot
    max_val = max(process_val);
    overshoot = 0;
    if max_val > final_value
        overshoot = ((max_val - final_value) / final_value) * 100;
    end
    
    % Find settling time (time to enter 2% error band and stay there)
    tolerance = 0.02 * final_value;
    lower_bound = final_value - tolerance;
    upper_bound = final_value + tolerance;
    settling_time = 0;
    
    for j = 1:length(time)
        if process_val(j) >= lower_bound && process_val(j) <= upper_bound
            % Check if all subsequent values are within bounds
            if all(process_val(j:end) >= lower_bound & process_val(j:end) <= upper_bound)
                settling_time = time(j);
                break;
            end
        end
    end
    
    % Calculate steady state error
    steady_state_error = abs(final_value - process_val(end));
    
    % Display performance metrics
    fprintf('=== %s Performance Metrics ===\n', controller_name);
    fprintf('Rise Time: %.2f seconds\n', rise_time);
    fprintf('Overshoot: %.2f%%\n', overshoot);
    fprintf('Settling Time: %.2f seconds\n', settling_time);
    fprintf('Steady State Error: %.6f\n\n', steady_state_error);
    
    % Store metrics for bar plot
    metrics(i, 1) = rise_time;
    metrics(i, 2) = overshoot;
    metrics(i, 3) = settling_time;
    metrics(i, 4) = steady_state_error;
end

% Add legend to plots
controller_names = controllers(:, 1);
subplot(3, 2, 1);
legend(controller_names, 'Location', 'best');

subplot(3, 2, 2);
legend(controller_names, 'Location', 'best');

% Plot performance metrics as bar charts
metric_names = {'Rise Time (s)', 'Overshoot (%)', 'Settling Time (s)', 'Steady State Error'};

% Create a new figure for performance metrics
figure('Name', 'Controller Performance Metrics', 'Position', [100, 100, 1200, 800]);

for i = 1:4
    subplot(2, 2, i);
    bar(1:4, metrics(:, i), 'FaceColor', 'flat');
    hold on;
    for j = 1:4
        bar(j, metrics(j, i), 'FaceColor', colors{j});
    end
    grid on;
    xlabel('Controller');
    ylabel(metric_names{i});
    title(sprintf('%s Comparison', metric_names{i}));
    set(gca, 'XTick', 1:4, 'XTickLabel', controller_names);
    xtickangle(45);
end

% Adjust layout for the first figure
figure(1);
subplot(3, 2, 1);
ylim([0, 1.5]);  % Adjust y-axis limit for better visualization

% Adjust figure position for better display
set(gcf, 'Position', [100, 100, 1200, 800]);

% Adjust position of subplots manually for better spacing
figure(2);
set(gcf, 'Position', [100, 100, 1200, 800]);

% Save the figure
saveas(gcf, 'controller_response_comparison.png');
fprintf('Plot saved as controller_response_comparison.png\n');

% Instructions for users
fprintf('\n=== Instructions ===\n');
fprintf('1. Make sure the CSV files are in the build directory\n');
fprintf('2. Run this script in MATLAB\n');
fprintf('3. The script will plot response curves and performance metrics for all controllers\n');
fprintf('4. You can modify the csv_dir variable to match your actual CSV file location\n');
fprintf('5. The plot will be saved as controller_response_comparison.png\n');
